// Code generated by mockery v1.0.0. DO NOT EDIT.

package hello

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGreeterServer is an autogenerated mock type for the GreeterServer type
type MockGreeterServer struct {
	mock.Mock
}

// SayHello provides a mock function with given fields: _a0, _a1
func (_m *MockGreeterServer) SayHello(_a0 context.Context, _a1 *HelloRequest) (*HelloReply, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *HelloReply
	if rf, ok := ret.Get(0).(func(context.Context, *HelloRequest) *HelloReply); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*HelloReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *HelloRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedGreeterServer provides a mock function with given fields:
func (_m *MockGreeterServer) mustEmbedUnimplementedGreeterServer() {
	_m.Called()
}
