// Code generated by mockery v1.0.0. DO NOT EDIT.

package hello

import mock "github.com/stretchr/testify/mock"

// MockUnsafeGreeterServer is an autogenerated mock type for the UnsafeGreeterServer type
type MockUnsafeGreeterServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGreeterServer provides a mock function with given fields:
func (_m *MockUnsafeGreeterServer) mustEmbedUnimplementedGreeterServer() {
	_m.Called()
}
